/usr/bin/tinyvpn -s -l0.0.0.0:50150 -f20:10 -k "kSf[8I8Ep2D]n4" --sub-net 10.7.0.0 --tun-dev tun0

iptables -t nat -A POSTROUTING -s 10.7.0.1/16 ! -d 10.7.0.1/16 -m comment --comment "tinyvpn" -j MASQUERADE
iptables -A FORWARD -s 10.7.0.1/16 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -d 10.7.0.1/16 -j ACCEPT
iptables -t mangle -A FORWARD -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

killall tinyvpn
iptables -t nat -D POSTROUTING -s 10.7.0.1/16 ! -d $net -m comment --comment "tinyvpn" -j MASQUERADE
iptables -D FORWARD -s 10.7.0.1/16 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -D FORWARD -d 10.7.0.1/16 -j ACCEPT
iptables -t mangle -D FORWARD -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

/usr/bin/tinyvpn -c -r47.79.93.210:50150 -f20:10 -k "kSf[8I8Ep2D]n4" --sub-net 10.7.0.0 --tun-dev tun0
